from __future__ import annotations

from types import ModuleType
from typing import Any

# 来自 rs_czsc 的类型，保持宽松
from rs_czsc import WeightBacktest as WeightBacktest
from rs_czsc import daily_performance as daily_performance
from rs_czsc import top_drawdowns as top_drawdowns

from . import envs as envs
from . import traders as traders
from . import utils as utils
from .core import (
    CZSC,
    ZS,
    CzscJsonStrategy,
    CzscStrategyBase,
    Direction,
    Event,
    Freq,
    NewBar,
    Operate,
    Position,
    RawBar,
    Signal,
    format_standard_kline,
)
from .eda import (
    cal_symbols_factor,
    cal_trade_price,
    cal_yearly_days,
    cross_sectional_strategy,
    dif_long_bear,
    limit_leverage,
    make_price_features,
    mark_cta_periods,
    mark_volatility,
    min_max_limit,
    monotonicity,
    remove_beta_effects,
    rolling_layers,
    sma_long_bear,
    tsf_type,
    turnover_rate,
    twap,
    unify_weights,
    vwap,
    weights_simple_ensemble,
)
from .traders import (
    CzscSignals,
    CzscTrader,
    SignalsParser,
    check_signals_acc,
    generate_czsc_signals,
    get_signals_config,
    get_signals_freqs,
    get_unique_signals,
)
from .utils import (
    AliyunOSS,
    DataClient,
    DiskCache,
    clear_cache,
    clear_expired_cache,
    code_namespace,
    create_grid_params,
    cross_sectional_ic,
    dill_dump,
    dill_load,
    disk_cache,
    empty_cache_path,
    fernet_decrypt,
    fernet_encrypt,
    freqs_sorted,
    generate_fernet_key,
    get_dir_size,
    get_py_namespace,
    get_url_token,
    holds_performance,
    home_path,
    import_by_name,
    index_composition,
    mac_address,
    overlap,
    print_df_sample,
    psi,
    read_json,
    resample_to_daily,
    risk_free_returns,
    rolling_daily_performance,
    save_json,
    set_url_token,
    ta,
    timeout_decorator,
    to_arrow,
    update_bbars,
    update_nxb,
    update_tbars,
    x_round,
)

__version__: str
__author__: str
__email__: str
__date__: str

# 延迟模块（运行时由 __getattr__ 注入）
svc: ModuleType
fsa: ModuleType
aphorism: ModuleType
mock: ModuleType
cwc: ModuleType

__all__ = [
    "WeightBacktest",
    "daily_performance",
    "top_drawdowns",
    "envs",
    "traders",
    "utils",
    "CZSC",
    "ZS",
    "Direction",
    "Event",
    "Freq",
    "NewBar",
    "Operate",
    "Position",
    "RawBar",
    "Signal",
    "format_standard_kline",
    "CzscSignals",
    "CzscTrader",
    "SignalsParser",
    "check_signals_acc",
    "generate_czsc_signals",
    "get_signals_config",
    "get_signals_freqs",
    "get_unique_signals",
    "AliyunOSS",
    "DataClient",
    "DiskCache",
    "clear_cache",
    "clear_expired_cache",
    "code_namespace",
    "create_grid_params",
    "cross_sectional_ic",
    "dill_dump",
    "dill_load",
    "disk_cache",
    "empty_cache_path",
    "fernet_decrypt",
    "fernet_encrypt",
    "freqs_sorted",
    "generate_fernet_key",
    "get_dir_size",
    "get_py_namespace",
    "get_url_token",
    "holds_performance",
    "home_path",
    "import_by_name",
    "index_composition",
    "mac_address",
    "overlap",
    "print_df_sample",
    "psi",
    "read_json",
    "resample_to_daily",
    "risk_free_returns",
    "rolling_daily_performance",
    "save_json",
    "set_url_token",
    "ta",
    "timeout_decorator",
    "to_arrow",
    "update_bbars",
    "update_nxb",
    "update_tbars",
    "x_round",
    "svc",
    "fsa",
    "aphorism",
    "mock",
    "cwc",
    "CzscStrategyBase",
    "CzscJsonStrategy",
    "capture_warnings",
    "execute_with_warning_capture",
    "adjust_holding_weights",
    "log_strategy_info",
    "calculate_bi_info",
    "symbols_bi_infos",
    "plot_czsc_chart",
    "KlineChart",
    "check_kline_quality",
    "remove_beta_effects",
    "vwap",
    "twap",
    "cross_sectional_strategy",
    "monotonicity",
    "min_max_limit",
    "rolling_layers",
    "cal_symbols_factor",
    "weights_simple_ensemble",
    "unify_weights",
    "sma_long_bear",
    "dif_long_bear",
    "tsf_type",
    "limit_leverage",
    "cal_trade_price",
    "mark_cta_periods",
    "mark_volatility",
    "cal_yearly_days",
    "turnover_rate",
    "make_price_features",
    "__version__",
    "__author__",
    "__email__",
    "__date__",
    "welcome",
]

def __getattr__(name: str) -> Any: ...
def welcome() -> None: ...
