"""
czsc 核心对象转发模块

本模块作为 rs_czsc Rust 扩展的 Python 桥接层，
集中导入并暴露所有核心类与函数。无独立业务逻辑。

如需强制使用 Python 实现，设置环境变量 CZSC_USE_PYTHON=1
"""

from rs_czsc import (
    BI,
    CZSC,
    FX,
    ZS,
    BarGenerator,
    CzscExitOptimStrategy,
    CzscJsonStrategy,
    CzscOpenOptimStrategy,
    CzscStrategyBase,
    Direction,
    Event,
    ExitsOptimize,
    FakeBI,
    Freq,
    Mark,
    NewBar,
    OpensOptimize,
    Operate,
    ParsedSignalDoc,
    Position,
    RawBar,
    Signal,
    WeightBacktest,
    build_exit_optim_positions,
    build_open_optim_positions,
    build_strategy_config,
    daily_performance,
    derive_signals_config,
    derive_signals_freqs,
    format_standard_kline,
    normalize_feature,
    parse_signal_doc,
    run_optimize_batch,
    run_replay,
    run_research,
    top_drawdowns,
)

__all__ = [
    "Operate",
    "Freq",
    "Mark",
    "Direction",
    "CZSC",
    "BarGenerator",
    "format_standard_kline",
    "RawBar",
    "NewBar",
    "FX",
    "BI",
    "FakeBI",
    "ZS",
    "Signal",
    "Event",
    "Position",
    "WeightBacktest",
    "CzscStrategyBase",
    "CzscJsonStrategy",
    "CzscOpenOptimStrategy",
    "CzscExitOptimStrategy",
    "OpensOptimize",
    "ExitsOptimize",
    "run_research",
    "run_replay",
    "run_optimize_batch",
    "build_open_optim_positions",
    "build_exit_optim_positions",
    "build_strategy_config",
    "top_drawdowns",
    "daily_performance",
    "normalize_feature",
    "parse_signal_doc",
    "ParsedSignalDoc",
    "derive_signals_config",
    "derive_signals_freqs",
]
