import pandas as pd

def monotonicity(sequence): ...
def cal_yearly_days(dts: list, **kwargs): ...
def weights_simple_ensemble(df, weight_cols, method: str = "mean", only_long: bool = False, **kwargs): ...
def cal_trade_price(df: pd.DataFrame, digits=None, **kwargs): ...
def mark_cta_periods(df: pd.DataFrame, **kwargs): ...
def mark_volatility(df: pd.DataFrame, kind: str = "ts", **kwargs): ...
def turnover_rate(df: pd.DataFrame, **kwargs): ...
