# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
import typing
__all__ = [
    "BI",
    "BarGenerator",
    "CZSC",
    "CzscSignals",
    "CzscTrader",
    "Direction",
    "Event",
    "FX",
    "FakeBI",
    "Freq",
    "LiteBar",
    "Mark",
    "Market",
    "NewBar",
    "Operate",
    "ParsedSignalDoc",
    "Pos",
    "Position",
    "RawBar",
    "Signal",
    "ZS",
    "chip_distribution_triangle",
    "monotonicity",
    "parse_signal_doc",
]

@typing.final
class BI:
    r"""
    笔
    """
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def direction(self) -> Direction: ...
    @property
    def high(self) -> builtins.float: ...
    @property
    def low(self) -> builtins.float: ...
    @property
    def cache(self) -> typing.Any:
        r"""
        缓存字典（与 czsc 库兼容）
        """
    @property
    def __dict__(self) -> typing.Any:
        r"""
        直接支持 __dict__ 属性，让 pandas DataFrame() 能正确识别对象
        """
    @property
    def sdt(self) -> typing.Any: ...
    @property
    def edt(self) -> typing.Any: ...
    @property
    def fx_a(self) -> FX: ...
    @property
    def fx_b(self) -> FX: ...
    @property
    def fxs(self) -> builtins.list[FX]: ...
    @property
    def bars(self) -> builtins.list[NewBar]:
        r"""
        获取构成笔的NewBar列表
        """
    @property
    def power(self) -> builtins.float:
        r"""
        价差力度
        """
    @property
    def power_price(self) -> builtins.float:
        r"""
        价差力度（别名）
        """
    @property
    def power_volume(self) -> builtins.float:
        r"""
        成交量力度
        """
    @property
    def power_snr(self) -> builtins.float:
        r"""
        SNR 度量力度
        """
    @property
    def change(self) -> builtins.float:
        r"""
        笔的涨跌幅
        """
    @property
    def SNR(self) -> builtins.float:
        r"""
        笔内部的信噪比
        """
    @property
    def slope(self) -> builtins.float:
        r"""
        笔内部高低点之间的斜率
        """
    @property
    def acceleration(self) -> builtins.float:
        r"""
        笔内部价格的加速度
        """
    @property
    def length(self) -> builtins.int:
        r"""
        笔的无包含关系K线数量
        """
    @property
    def rsq(self) -> builtins.float:
        r"""
        笔的原始K线close单变量线性回归拟合优度
        """
    @property
    def hypotenuse(self) -> builtins.float:
        r"""
        笔的斜边长度
        """
    @property
    def angle(self) -> builtins.float:
        r"""
        笔的斜边与竖直方向的夹角，角度越大，力度越大
        """
    @property
    def raw_bars(self) -> builtins.list[RawBar]:
        r"""
        构成笔的原始K线序列，不包含首尾分型的首根K线
        """
    @property
    def fake_bis(self) -> builtins.list[FakeBI]:
        r"""
        笔的内部分型连接得到近似次级别笔列表
        """
    def __new__(cls, symbol: builtins.str, direction: Direction, fx_a: FX, fx_b: FX, fxs: typing.Sequence[FX], bars: typing.Sequence[NewBar]) -> BI: ...
    def get_cache_with_default(self, _key: builtins.str, default_value: builtins.float) -> builtins.float:
        r"""
        获取缓存值，如果不存在则返回默认值（与 czsc 库兼容）
        """
    def get_price_linear(self, n: builtins.int) -> builtins.float:
        r"""
        获取线性价格（与 czsc 库兼容）
        """
    def __repr__(self) -> builtins.str: ...
    def __richcmp__(self, other: BI, op: int) -> builtins.bool: ...

@typing.final
class BarGenerator:
    @property
    def symbol(self) -> typing.Optional[builtins.str]:
        r"""
        获取所属品种 - Python 属性
        """
    @property
    def base_freq(self) -> builtins.str:
        r"""
        获取基准频率
        """
    @property
    def end_dt(self) -> typing.Optional[typing.Any]:
        r"""
        获取end_dt属性（Python兼容）
        """
    @property
    def bars(self) -> typing.Any:
        r"""
        获取各周期K线数据 - 返回字典，键为频率字符串，值为K线列表
        """
    def __new__(cls, base_freq: typing.Any, freqs: typing.Any, max_count: builtins.int = 2000, market: typing.Optional[typing.Any] = None) -> BarGenerator: ...
    def init_freq_bars(self, freq: typing.Any, bars: typing.Sequence[RawBar]) -> None:
        r"""
        初始化某个周期的K线序列
        
        # 函数计算逻辑
        
        1. 检查输入的`freq`是否存在于`self.freq_bars`的键中。如果不存在，返回错误。
        2. 检查`self.freq_bars[freq]`是否为空。如果不为空，返回错误，表示不允许重复初始化。
        3. 如果以上检查都通过，将输入的`bars`存储到`self.freq_bars[freq]`中。
        4. 从`bars`中获取最后一根K线的交易标的代码，更新`self.symbol`。
        
        # Arguments
        
        * `freq` - 周期名称 (支持字符串或Freq枚举)
        * `bars` - K线序列
        """
    def get_latest_date(self) -> typing.Optional[builtins.str]:
        r"""
        获取最新K线日期
        """
    def update(self, bar: RawBar) -> None:
        r"""
        从Python RawBar对象更新K线数据 - 支持直接自动转换
        """
    def __reduce__(self) -> typing.Any:
        r"""
        支持 pickle 序列化 - 使用 __reduce__ 方法
        """
    def __setstate__(self, state: typing.Any) -> None:
        r"""
        支持 pickle 反序列化
        """

@typing.final
class CZSC:
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def freq(self) -> Freq: ...
    @property
    def max_bi_num(self) -> builtins.int: ...
    @property
    def bi_list(self) -> builtins.list[BI]: ...
    @property
    def bars_raw(self) -> builtins.list[RawBar]:
        r"""
        获取原始K线序列 - 返回PyRawBar对象列表
        """
    @property
    def bars_raw_df(self) -> typing.Any:
        r"""
        获取原始K线序列的DataFrame格式，便于绘图和分析
        """
    @property
    def bars_ubi(self) -> builtins.list[NewBar]:
        r"""
        获取无包含关系K线序列
        """
    @property
    def finished_bis(self) -> builtins.list[BI]:
        r"""
        获取已完成的笔列表（与 bi_list 相同，为兼容 czsc 库）
        """
    @property
    def fx_list(self) -> builtins.list[FX]:
        r"""
        获取分型列表（属性，与 czsc 库兼容）
        """
    @property
    def cache(self) -> dict:
        r"""
        缓存字典（与 czsc 库兼容）
        """
    @property
    def signals(self) -> typing.Any:
        r"""
        信号字典（与 czsc 库兼容）
        """
    @property
    def ubi_fxs(self) -> builtins.list[FX]:
        r"""
        无包含关系K线分型列表（与 czsc 库兼容）
        """
    @property
    def ubi(self) -> typing.Any:
        r"""
        无包含关系K线（与 czsc 库兼容）
        返回未完成的笔信息，格式与 Python 版本保持一致
        """
    @property
    def verbose(self) -> builtins.bool:
        r"""
        是否显示详细信息（与 czsc 库兼容）
        """
    @property
    def last_bi_extend(self) -> builtins.bool:
        r"""
        最后一笔延伸情况（与 czsc 库兼容）
        判断最后一笔是否在延伸中，True 表示延伸中
        """
    def __new__(cls, bars_raw: typing.Sequence[RawBar], max_bi_num: builtins.int = 50) -> CZSC: ...
    @staticmethod
    def from_dataframe(df_bytes: bytes, freq: Freq, max_bi_num: builtins.int = 50) -> CZSC:
        r"""
        直接从Arrow格式的DataFrame创建CZSC对象，避免中间转换
        这是高性能的批量创建接口，适用于大量数据的初始化
        
        :param df_bytes: Arrow IPC格式的DataFrame字节数据
        :param freq: K线频率
        :param max_bi_num: 最大笔数量限制
        :return: CZSC对象
        """
    def open_in_browser(self, _renderer: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        在浏览器中打开（与 czsc 库兼容）
        """
    def to_echarts(self) -> builtins.str:
        r"""
        转换为 ECharts 格式（与 czsc 库兼容）
        """
    def to_plotly(self) -> builtins.str:
        r"""
        转换为 Plotly 格式（与 czsc 库兼容）
        """
    def update(self, bar: RawBar) -> None:
        r"""
        更新K线数据
        """
    def __repr__(self) -> builtins.str: ...
    def __reduce__(self) -> typing.Any:
        r"""
        Pickle 支持 —— `__reduce__` 返回 ``(CZSC, (fixed_point_bars, max_bi_num))``。
        
        `update_bar` 会丢弃 dt 小于当前 first-BI 起始时间的旧 bar
        （参见上面的 `bars_raw.drain` 块），因此刚构造出来的 CZSC 的
        `bars_raw` 可能仍然和「再分析一次后到达的不动点」不同。这里多
        跑一次 `CZSC::new`，让其在序列化前收敛 —— 保证即使 CzscSignals
        在 `kas[freq]` 里嵌套了 CZSC，`pickle.dumps(restored) ==
        pickle.dumps(obj)` 也是逐字节相等的（Phase A 的
        `restored.__getstate__() == obj.__getstate__()` 断言依赖这一点）。
        """

@typing.final
class CzscSignals:
    r"""
    CzscSignals 的 PyO3 包装
    """
    @property
    def name(self) -> builtins.str:
        r"""
        返回类名
        """
    @property
    def symbol(self) -> builtins.str:
        r"""
        返回标的代码
        """
    @property
    def s(self) -> typing.Any:
        r"""
        返回信号字典 s
        """
    @property
    def kas(self) -> builtins.dict[builtins.str, CZSC]:
        r"""
        返回各周期 CZSC 分析引擎
        """
    @property
    def freqs(self) -> builtins.list[builtins.str]:
        r"""
        返回所有周期字符串列表
        """
    @property
    def base_freq(self) -> builtins.str:
        r"""
        返回基准周期字符串
        """
    @property
    def end_dt(self) -> typing.Optional[typing.Any]:
        r"""
        返回最新时间，作为 pandas Timestamp
        """
    @property
    def bid(self) -> typing.Optional[builtins.int]:
        r"""
        返回当前 bar id
        """
    @property
    def latest_price(self) -> typing.Optional[builtins.float]:
        r"""
        返回最新价格
        """
    @property
    def signals_config(self) -> typing.Any:
        r"""
        返回原始信号配置
        """
    def __new__(cls, bg: BarGenerator, signals_config: list) -> CzscSignals: ...
    def update_signals(self, bar: RawBar) -> None:
        r"""
        更新信号。
        
        BarGenerator 现在会对 NaN OHLCV / freq mismatch 等硬错返回 Err，
        这里 propagate 成 Python ValueError，避免吞 Err 让信号链路用 stale 状态。
        """
    def get_signals_by_conf(self) -> typing.Any:
        r"""
        获取当前信号字典（同 s 属性）
        """
    def __reduce__(self) -> typing.Any:
        r"""
        Pickle 支持：返回 ``(cls, (bg_clone, signals_config_list))``。
        反序列化时 PyCzscSignals 由原 ``__new__`` 重新构造；缓存的信号
        状态不持久化（与 design doc §2.4 的 multiprocessing 用例一致：
        子进程拿到的是构造参数 fresh trader）。
        """

@typing.final
class CzscTrader:
    r"""
    CzscTrader 的 PyO3 包装
    """
    @property
    def name(self) -> builtins.str:
        r"""
        返回类名
        """
    @property
    def symbol(self) -> builtins.str:
        r"""
        返回标的代码
        """
    @property
    def s(self) -> typing.Any:
        r"""
        返回信号字典 s
        """
    @property
    def kas(self) -> builtins.dict[builtins.str, CZSC]:
        r"""
        返回各周期 CZSC 分析引擎
        """
    @property
    def freqs(self) -> builtins.list[builtins.str]:
        r"""
        返回所有周期字符串列表
        """
    @property
    def base_freq(self) -> builtins.str:
        r"""
        返回基准周期字符串
        """
    @property
    def end_dt(self) -> typing.Optional[typing.Any]:
        r"""
        返回最新时间，作为 pandas Timestamp
        """
    @property
    def bid(self) -> typing.Optional[builtins.int]:
        r"""
        返回当前 bar id
        """
    @property
    def latest_price(self) -> typing.Optional[builtins.float]:
        r"""
        返回最新价格
        """
    @property
    def signals_config(self) -> typing.Any:
        r"""
        返回原始信号配置
        """
    @property
    def positions(self) -> builtins.list[Position]:
        r"""
        返回仓位列表（PyPosition 包装）
        """
    @property
    def pos_changed(self) -> builtins.bool:
        r"""
        返回是否有仓位发生变化
        """
    def __new__(cls, bg: BarGenerator, positions: list, signals_config: list, ensemble_method: builtins.str = 'mean') -> CzscTrader: ...
    def update(self, bar: RawBar) -> None:
        r"""
        更新信号和仓位。
        
        BarGenerator 现在会对 NaN OHLCV / freq mismatch 等硬错返回 Err，
        这里 propagate 成 Python ValueError 避免吞 Err 让信号 / 仓位用 stale 状态。
        """
    def on_bar(self, bar: RawBar) -> None:
        r"""
        更新信号和仓位（同 update）
        """
    def on_sig(self, sig: dict) -> None:
        r"""
        基于信号字典更新仓位
        """
    def get_ensemble_pos(self, method: typing.Optional[builtins.str] = None) -> builtins.float:
        r"""
        获取集成后的仓位值
        """
    def get_position(self, name: builtins.str) -> typing.Optional[Position]:
        r"""
        根据名称获取仓位
        """
    def get_signals_by_conf(self) -> typing.Any:
        r"""
        获取当前信号字典
        """
    def update_signals(self, bar: RawBar) -> None:
        r"""
        仅更新信号（不更新仓位）。
        
        同 update：BarGenerator 硬错 propagate 成 Python ValueError。
        """
    def dump_state(self) -> bytes:
        r"""
        导出完整状态快照为 bytes（热启动用，零重放）。
        
        快照含缠论计算状态（bg/kas/ta_cache 全历史）、仓位配置与运行时决策状态
        （pos/operates/holds 等）、信号配置与集成方式，可经 ``restore_state`` 单参还原。
        """
    @staticmethod
    def restore_state(data: bytes) -> CzscTrader:
        r"""
        从 ``dump_state`` 产生的 bytes 还原 trader（零重放热启动）。
        
        信号配置与集成方式从快照内读回，无需额外参数。
        """
    def __reduce__(self) -> typing.Any:
        r"""
        Pickle 支持：返回构造参数 (bg, positions, signals_config, ensemble_method)。
        反序列化时由 ``__new__`` 重新构造一个 fresh trader；缓存的运行
        状态不持久化（与 design doc §2.4 multiprocessing 用例一致）。
        """

@typing.final
class Event:
    r"""
    Python可见的Event包装器
    """
    @property
    def operate(self) -> Operate: ...
    @property
    def signals_all(self) -> builtins.list[Signal]: ...
    @property
    def signals_any(self) -> builtins.list[Signal]: ...
    @property
    def signals_not(self) -> builtins.list[Signal]: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def unique_signals(self) -> builtins.list[builtins.str]:
        r"""
        获取所有唯一信号（字符串格式，兼容原Python API）
        """
    @property
    def sha256(self) -> builtins.str:
        r"""
        获取SHA256哈希
        """
    def __new__(cls, operate: Operate, signals_all: typing.Sequence[Signal] = [], signals_any: typing.Sequence[Signal] = [], signals_not: typing.Sequence[Signal] = [], name: builtins.str = '') -> Event: ...
    @classmethod
    def from_dict(cls, dict: dict) -> Event: ...
    @classmethod
    def from_json(cls, json_str: builtins.str) -> Event: ...
    def compute_sha8(self) -> builtins.str:
        r"""
        计算SHA8哈希值
        """
    def is_match(self, signals: typing.Any) -> builtins.bool:
        r"""
        判断事件是否匹配信号集合，返回是否匹配
        支持多种参数类型：Dict[str, str] 或 Dict[str, Signal] 或 Vec<PySignal>
        """
    def to_json(self) -> builtins.str:
        r"""
        转换为JSON字符串
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self) -> typing.Any:
        r"""
        导出为字典
        """
    @classmethod
    def load(cls, data: dict) -> Event:
        r"""
        从字典加载
        """
    def get_signals_config(self) -> builtins.list[builtins.str]:
        r"""
        获取信号配置
        """
    def __reduce__(self) -> typing.Any:
        r"""
        支持 pickle 序列化 - 使用 __reduce__ 方法
        """

@typing.final
class FX:
    r"""
    分型
    """
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def dt(self) -> typing.Any: ...
    @property
    def mark(self) -> Mark: ...
    @property
    def high(self) -> builtins.float: ...
    @property
    def low(self) -> builtins.float: ...
    @property
    def fx(self) -> builtins.float: ...
    @property
    def new_bars(self) -> builtins.list[NewBar]:
        r"""
        获取构成分型的NewBar列表
        """
    @property
    def raw_bars(self) -> builtins.list[RawBar]:
        r"""
        获取原始K线列表（从NewBar的elements中提取）
        """
    @property
    def power_str(self) -> builtins.str:
        r"""
        获取分型强度字符串
        """
    @property
    def power_volume(self) -> builtins.float:
        r"""
        获取成交量力度
        """
    @property
    def has_zs(self) -> builtins.bool:
        r"""
        判断是否有重叠中枢
        """
    @property
    def elements(self) -> builtins.list[NewBar]:
        r"""
        获取构成分型的NewBar列表（与new_bars相同，为兼容czsc库）
        """
    @property
    def cache(self) -> dict:
        r"""
        缓存字典（与 czsc 库兼容）
        """
    @property
    def __dict__(self) -> typing.Any:
        r"""
        直接支持 __dict__ 属性，让 pandas DataFrame() 能正确识别对象
        """
    def __new__(cls, symbol: builtins.str, dt: typing.Any, mark: Mark, high: builtins.float, low: builtins.float, fx: builtins.float, elements: typing.Sequence[NewBar]) -> FX: ...
    def __repr__(self) -> builtins.str: ...
    def __richcmp__(self, other: FX, op: int) -> builtins.bool: ...

@typing.final
class FakeBI:
    r"""
    虚拟笔
    主要为笔的内部分析提供便利
    """
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def sdt(self) -> typing.Any: ...
    @property
    def edt(self) -> typing.Any: ...
    @property
    def direction(self) -> Direction: ...
    @property
    def high(self) -> builtins.float: ...
    @property
    def low(self) -> builtins.float: ...
    @property
    def power(self) -> builtins.float: ...
    @property
    def cache(self) -> dict: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LiteBar:
    r"""
    Python可见的LiteBar包装器
    """
    @property
    def id(self) -> builtins.int: ...
    @property
    def dt(self) -> builtins.float: ...
    @property
    def price(self) -> builtins.float: ...
    def __new__(cls, id: builtins.int, dt: builtins.float, price: builtins.float) -> LiteBar: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class NewBar:
    r"""
    去除包含关系后的K线元素
    """
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def dt(self) -> typing.Any: ...
    @property
    def freq(self) -> Freq: ...
    @property
    def id(self) -> builtins.int: ...
    @property
    def open(self) -> builtins.float: ...
    @property
    def close(self) -> builtins.float: ...
    @property
    def high(self) -> builtins.float: ...
    @property
    def low(self) -> builtins.float: ...
    @property
    def vol(self) -> builtins.float: ...
    @property
    def amount(self) -> builtins.float: ...
    @property
    def cache(self) -> dict: ...
    @property
    def elements(self) -> builtins.list[RawBar]: ...
    @property
    def raw_bars(self) -> builtins.list[RawBar]:
        r"""
        获取构成NewBar的原始K线列表（与elements相同，为兼容czsc库）
        """
    def __new__(cls, symbol: builtins.str, dt: typing.Any, freq: Freq, open: builtins.float, close: builtins.float, high: builtins.float, low: builtins.float, vol: builtins.float, amount: builtins.float, id: builtins.int = 0, elements: typing.Optional[typing.Sequence[RawBar]] = None) -> NewBar: ...
    def __repr__(self) -> builtins.str: ...
    def __richcmp__(self, other: NewBar, op: int) -> builtins.bool: ...

@typing.final
class Operate:
    r"""
    Python可见的Operate包装器
    """
    HL: Operate
    HS: Operate
    HO: Operate
    LO: Operate
    LE: Operate
    SO: Operate
    SE: Operate
    @property
    def value(self) -> builtins.str:
        r"""
        兼容性属性：返回操作类型的中文字符串值
        """
    @property
    def name(self) -> builtins.str:
        r"""
        返回 Rust variant 名（"HL" / "HS" / "HO" / "LO" / "LE" / "SO" / "SE"），
        对齐 Python `enum.Enum.name`：英文标识符稳定且与序列化路径
        (`from_str` / `to_string`) 一致，适合做配置 key / 日志短码。
        """
    @classmethod
    def hl(cls) -> Operate: ...
    @classmethod
    def hs(cls) -> Operate: ...
    @classmethod
    def ho(cls) -> Operate: ...
    @classmethod
    def lo(cls) -> Operate: ...
    @classmethod
    def le(cls) -> Operate: ...
    @classmethod
    def so(cls) -> Operate: ...
    @classmethod
    def se(cls) -> Operate: ...
    @classmethod
    def from_str_py(cls, s: builtins.str) -> Operate: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> Operate: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Operate) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __reduce__(self) -> typing.Any:
        r"""
        支持pickle序列化
        """

@typing.final
class ParsedSignalDoc:
    r"""
    Python可见的ParsedSignalDoc包装器
    """
    @property
    def param_template(self) -> typing.Optional[builtins.str]: ...
    @property
    def signals(self) -> builtins.list[Signal]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Pos:
    r"""
    Python可见的Pos枚举包装器
    """
    @classmethod
    def short(cls) -> Pos: ...
    @classmethod
    def flat(cls) -> Pos: ...
    @classmethod
    def long(cls) -> Pos: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Pos) -> builtins.bool: ...
    def __add__(self, other: Pos) -> builtins.float:
        r"""
        加法运算，用于numpy.mean等数学操作
        """
    def __radd__(self, other: builtins.float) -> builtins.float:
        r"""
        右加法运算
        """
    def __float__(self) -> builtins.float:
        r"""
        转换为浮点数，用于数学运算
        """
    def __int__(self) -> builtins.int:
        r"""
        整数转换
        """
    def __lt__(self, other: Pos) -> builtins.bool:
        r"""
        比较运算符 - 小于
        """
    def __le__(self, other: Pos) -> builtins.bool:
        r"""
        比较运算符 - 小于等于
        """
    def __gt__(self, other: Pos) -> builtins.bool:
        r"""
        比较运算符 - 大于
        """
    def __ge__(self, other: Pos) -> builtins.bool:
        r"""
        比较运算符 - 大于等于
        """

@typing.final
class Position:
    r"""
    Python可见的Position包装器
    """
    @property
    def opens(self) -> builtins.list[Event]: ...
    @property
    def exits(self) -> builtins.list[Event]: ...
    @property
    def interval(self) -> builtins.int: ...
    @property
    def timeout(self) -> builtins.int: ...
    @property
    def stop_loss(self) -> builtins.float: ...
    @property
    def t0(self) -> builtins.bool: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def pos(self) -> builtins.float: ...
    @property
    def pos_changed(self) -> builtins.bool: ...
    @property
    def end_dt(self) -> typing.Optional[builtins.float]:
        r"""
        获取最新信号时间
        """
    @property
    def operates(self) -> builtins.list[typing.Any]:
        r"""
        获取操作记录列表
        """
    @property
    def pairs(self) -> list:
        r"""
        获取交易对数据（返回记录列表，兼容pandas.DataFrame构造）
        """
    @property
    def holds(self) -> list:
        r"""
        获取持仓历史数据（返回记录列表，兼容历史版本）
        """
    @property
    def unique_signals(self) -> builtins.list[builtins.str]: ...
    @property
    def events(self) -> builtins.list[Event]: ...
    def __new__(cls, symbol: builtins.str, opens: typing.Sequence[Event], exits: typing.Sequence[Event] = [], interval: builtins.int = 0, timeout: builtins.int = 1000, stop_loss: builtins.float = 1000.0, t0: builtins.bool = False, name: typing.Optional[builtins.str] = None) -> Position: ...
    @classmethod
    def load_from_file(cls, path: builtins.str) -> Position: ...
    @classmethod
    def from_json(cls, json_str: builtins.str) -> Position: ...
    def save(self, path: builtins.str) -> None:
        r"""
        保存到文件
        """
    def to_json(self) -> builtins.str:
        r"""
        转换为JSON字符串
        """
    def all_events(self) -> builtins.list[Event]:
        r"""
        获取所有相关事件
        """
    def update(self, arg1: typing.Any, arg2: typing.Optional[typing.Any] = None) -> None:
        r"""
        更新仓位状态（兼容单参数调用）
        """
    def __reduce__(self) -> typing.Any:
        r"""
        支持 pickle 序列化 - 使用 __reduce__ 方法
        """
    def dump(self, with_data: builtins.bool = True) -> typing.Any:
        r"""
        导出Position数据为Python字典
        """
    @classmethod
    def load(cls, data: typing.Any) -> Position:
        r"""
        从字典数据加载Position
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RawBar:
    r"""
    原始K线元素
    """
    @property
    def symbol(self) -> builtins.str: ...
    @property
    def dt(self) -> typing.Any: ...
    @property
    def freq(self) -> Freq: ...
    @property
    def id(self) -> builtins.int: ...
    @property
    def open(self) -> builtins.float: ...
    @property
    def close(self) -> builtins.float: ...
    @property
    def high(self) -> builtins.float: ...
    @property
    def low(self) -> builtins.float: ...
    @property
    def vol(self) -> builtins.float: ...
    @property
    def amount(self) -> builtins.float: ...
    @property
    def solid(self) -> builtins.float:
        r"""
        实体部分（与原版CZSC兼容）
        """
    @property
    def upper(self) -> builtins.float:
        r"""
        上影线长度（与原版CZSC兼容）
        """
    @property
    def lower(self) -> builtins.float:
        r"""
        下影线长度（与原版CZSC兼容）
        """
    @property
    def cache(self) -> dict: ...
    @property
    def __dict__(self) -> typing.Any:
        r"""
        直接支持 __dict__ 属性，让 pandas DataFrame() 能正确识别对象
        """
    def __new__(cls, symbol: builtins.str, dt: typing.Any, freq: Freq, open: builtins.float, close: builtins.float, high: builtins.float, low: builtins.float, vol: builtins.float, amount: builtins.float, id: builtins.int = 0) -> RawBar: ...
    def _asdict(self) -> typing.Any:
        r"""
        让对象表现得像记录，pandas DataFrame构造器会调用这个
        """
    def to_dict(self) -> typing.Any:
        r"""
        转换为字典，便于创建 pandas DataFrame
        """
    def __reduce__(self) -> typing.Any:
        r"""
        支持pickle序列化
        """
    def __deepcopy__(self, _memo: typing.Any) -> RawBar:
        r"""
        支持深拷贝
        """
    def __repr__(self) -> builtins.str: ...
    def __richcmp__(self, other: RawBar, op: int) -> builtins.bool: ...

@typing.final
class Signal:
    r"""
    Python可见的Signal包装器
    """
    @property
    def key(self) -> builtins.str: ...
    @property
    def value(self) -> builtins.str: ...
    @property
    def k3(self) -> builtins.str: ...
    @property
    def v1(self) -> builtins.str: ...
    @property
    def v2(self) -> builtins.str: ...
    @property
    def v3(self) -> builtins.str: ...
    @property
    def score(self) -> builtins.int: ...
    @property
    def k1(self) -> builtins.str:
        r"""
        新增k1和k2属性getter，匹配Python版本
        """
    @property
    def k2(self) -> builtins.str: ...
    def __new__(cls, *args: typing.Any, signal: typing.Optional[builtins.str] = None, key: typing.Optional[builtins.str] = None, value: typing.Optional[builtins.str] = None, k1: typing.Optional[builtins.str] = None, k2: typing.Optional[builtins.str] = None, k3: typing.Optional[builtins.str] = None, v1: typing.Optional[builtins.str] = None, v2: typing.Optional[builtins.str] = None, v3: typing.Optional[builtins.str] = None, score: typing.Optional[builtins.int] = None) -> Signal: ...
    @classmethod
    def from_string(cls, s: builtins.str) -> Signal: ...
    def to_json(self) -> builtins.str:
        r"""
        添加to_json方法以匹配Python版本
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Signal) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def matches(self, other: Signal) -> builtins.bool:
        r"""
        检查Signal是否匹配另一个Signal
        """
    def is_match(self, signals_dict: typing.Mapping[builtins.str, builtins.str]) -> builtins.bool:
        r"""
        判断信号是否与信号字典中的值匹配（Python版本is_match逻辑）
        """
    def to_string(self) -> builtins.str:
        r"""
        获取Signal的完整字符串表示
        """

@typing.final
class ZS:
    @property
    def bis(self) -> builtins.list[BI]:
        r"""
        获取构成中枢的笔列表
        """
    @property
    def sdt(self) -> typing.Any:
        r"""
        中枢开始时间
        """
    @property
    def edt(self) -> typing.Any:
        r"""
        中枢结束时间
        """
    @property
    def sdir(self) -> Direction:
        r"""
        中枢第一笔方向
        """
    @property
    def edir(self) -> Direction:
        r"""
        中枢倒一笔方向
        """
    @property
    def zg(self) -> builtins.float:
        r"""
        中枢上沿
        """
    @property
    def zd(self) -> builtins.float:
        r"""
        中枢下沿
        """
    @property
    def zz(self) -> builtins.float:
        r"""
        中枢中轴
        """
    @property
    def gg(self) -> builtins.float:
        r"""
        中枢最高点
        """
    @property
    def dd(self) -> builtins.float:
        r"""
        中枢最低点
        """
    @property
    def cache(self) -> dict: ...
    def __new__(cls, bis: typing.Sequence[BI]) -> ZS: ...
    def is_valid(self) -> builtins.bool:
        r"""
        中枢是否有效
        """

@typing.final
class Direction(enum.Enum):
    r"""
    方向
    """
    Up = ...
    r"""
    向上
    """
    Down = ...
    r"""
    向下
    """

    @property
    def value(self) -> builtins.str:
        r"""
        获取方向的字符串值（与 czsc 库兼容）
        """
    @property
    def name(self) -> builtins.str:
        r"""
        返回 Rust variant 名（"Up" / "Down"），对齐 Python `enum.Enum.name`。
        """
    def __deepcopy__(self, _memo: typing.Any) -> Direction:
        r"""
        支持深拷贝
        """
    def __reduce__(self) -> tuple[typing.Any, typing.Any]:
        r"""
        支持pickle序列化
        """
    def __new__(cls, value: builtins.str) -> Direction: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int:
        r"""
        显式实现 `__hash__`，原因见 freq.rs 中同名方法的说明。
        """
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool: ...

@typing.final
class Freq(enum.Enum):
    r"""
    时间周期
    """
    Tick = ...
    r"""
    逐笔
    """
    F1 = ...
    r"""
    1分钟
    """
    F2 = ...
    r"""
    2分钟
    """
    F3 = ...
    r"""
    3分钟
    """
    F4 = ...
    r"""
    4分钟
    """
    F5 = ...
    r"""
    5分钟
    """
    F6 = ...
    r"""
    6分钟
    """
    F10 = ...
    r"""
    10分钟
    """
    F12 = ...
    r"""
    12分钟
    """
    F15 = ...
    r"""
    15分钟
    """
    F20 = ...
    r"""
    20分钟
    """
    F30 = ...
    r"""
    30分钟
    """
    F60 = ...
    r"""
    60分钟
    """
    F120 = ...
    r"""
    120分钟
    """
    F240 = ...
    r"""
    240分钟
    """
    F360 = ...
    r"""
    360分钟
    """
    D = ...
    r"""
    日线
    """
    W = ...
    r"""
    周线
    """
    M = ...
    r"""
    月线
    """
    S = ...
    r"""
    季线
    """
    Y = ...
    r"""
    年线
    """

    __members__: typing.Any
    @property
    def value(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str:
        r"""
        返回 Rust variant 名（"F30" / "D" / "Tick" / ...），
        对齐 Python `enum.Enum.name` 的习惯——便于在序列化、日志、
        配置文件里使用稳定且语言无关的英文标识符。
        """
    def __deepcopy__(self, _memo: typing.Any) -> Freq:
        r"""
        支持深拷贝
        """
    def __reduce__(self) -> tuple[typing.Any, typing.Any]:
        r"""
        支持pickle序列化
        """
    def __new__(cls, value: builtins.str) -> Freq: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int:
        r"""
        用 derived `Hash` 暴露 `__hash__`：PyO3 不会自动从 Rust 端
        `#[derive(Hash)]` 派生 Python `__hash__`，且一旦写了 `__richcmp__`
        又不显式给 `__hash__`，PyO3 会把 `__hash__` 显式设为 `None`，导致
        实例不可哈希（无法做 dict/set 的 key）。这里显式实现以恢复
        与 Python `enum.Enum` 一致的可哈希语义。
        """
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool: ...

@typing.final
class Mark(enum.Enum):
    r"""
    分型类型
    """
    D = ...
    r"""
    底分型
    """
    G = ...
    r"""
    顶分型
    """

    @property
    def value(self) -> builtins.str:
        r"""
        获取标记的字符串值（与 czsc 库兼容）
        """
    @property
    def name(self) -> builtins.str:
        r"""
        返回 Rust variant 名（"G" / "D"），对齐 Python `enum.Enum.name`。
        """
    def __deepcopy__(self, _memo: typing.Any) -> Mark:
        r"""
        支持深拷贝
        """
    def __reduce__(self) -> tuple[typing.Any, typing.Any]:
        r"""
        支持 pickle 序列化：参考 Direction 的实现，通过 `__reduce__`
        把实例还原成 `Mark("G")` / `Mark("D")` 的构造调用。
        """
    def __new__(cls, value: builtins.str) -> Mark:
        r"""
        支持从字符串构造（接受 Rust variant 名或中文显示串）。
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __hash__(self) -> builtins.int:
        r"""
        显式实现 `__hash__`，原因见 freq.rs 中同名方法的说明：PyO3 不会
        自动从 Rust `Hash` derive 派生 Python `__hash__`，且写了 `__richcmp__`
        后会把 `__hash__` 置 None。
        """
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool: ...

@typing.final
class Market(enum.Enum):
    AShare = ...
    r"""
    A股
    """
    Futures = ...
    r"""
    期货
    """
    Default = ...
    r"""
    默认
    """

    def __new__(cls, ob: typing.Any) -> Market: ...

def chip_distribution_triangle(data: numpy.typing.NDArray[numpy.float64], price_step: builtins.float, decay_factor: builtins.float) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
    r"""
    计算筹码分布（三角形分布 + 筹码沉淀机制）
    
    此函数用于估算基于历史K线的筹码分布情况，结合三角形分布模型和筹码沉淀（衰减）机制。
    
    # Python 接口说明
    
    输入一个二维 numpy 数组，形状为 (N, 3)，每一行对应一根K线，列顺序为：
    `[high, low, vol]`，类型必须为 `float64`。
    
    示例：
    ```python
    columns = ['high', 'low', 'vol']
    arr2 = df[columns].to_numpy(dtype=np.float64)
    price_centers, chip_dist = chip_distribution_triangle(arr2, 0.01, 0.9)
    ```
    
    # 参数
    
    - `data`: 二维数组，形状为 (N, 3)，分别是每根K线的最高价、最低价和成交量。
    - `price_step`: 分档间隔（如0.01表示以0.01为单位划分价格区间）。
    - `decay_factor`: 筹码衰减因子，表示前一根K线上的筹码有多少比例沉淀保留到下一根K线上，范围为(0, 1)，例如0.98表示保留98%。
    
    # 返回值
    
    返回一个元组 `(price_centers, chip_distribution)`:
    - `price_centers`: 一维数组，表示价格分布区间的中心价位。
    - `chip_distribution`: 一维数组，对应每个价格中心的筹码强度（权重/密度）。
    
    返回的两个数组长度相同，可用于绘制筹码分布图或进一步分析。
    """

def monotonicity(sequence: typing.Sequence[builtins.float]) -> builtins.float:
    r"""
    `czsc.monotonicity(sequence)` → float。
    
    计算序列与自然数序列的 Spearman 秩相关，等价于
    `scipy.stats.spearmanr(sequence, range(len(sequence))).statistic`。
    详见 [`crate::monotonicity::monotonicity`] 的算法说明与对齐口径。
    """

def parse_signal_doc(doc: builtins.str) -> ParsedSignalDoc:
    r"""
    解析文档中的Signal信息
    """

